valid_dataloader:
  - type: web_dataloader
    args:
      shards: ./data/imagenet/processed/train/imagenet-train-{000000..000639}.tar
      dataset_size: 1280000
      shuffle: 0
      num_workers: 16
      batch_size: 512
      train: true
      transform_type: val_bicubic_inter
  - type: web_dataloader
    args:
      shards: ./data/imagenet/processed/val/imagenet-val-{000000..000099}.tar
      dataset_size: 50000
      shuffle: 0
      num_workers: 16
      batch_size: 1
      train: false
      transform_type: val_bicubic_inter

evaluator:
  - type: KNNEvaluator
    args:
      log_name: '_final'
      k: [1, 10, 20, 50]
      num_classes: 1000
      temperature: 0.07
      mute_tqdm: false
#      compute_sim_on_cpu: false
